name: Publish Node.js app to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: production
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      PINATA_API_KEY: "760dce7dc7cbb3c93387"
      PINATA_API_SECRET: "31bec0dd5441e5dd1c20f32a487e4e8fe48633f40be5c71360db473e685d0703"
      PINATA_API_JWT: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI3YjViOTRjZi04OTJiLTRjNWEtYTQ4MC05NTY1MGNjNDJjMWMiLCJlbWFpbCI6Iml0dGVjaGh1bnRlcjUxM0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJpZCI6IkZSQTEiLCJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MX0seyJpZCI6Ik5ZQzEiLCJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MX1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiNzYwZGNlN2RjN2NiYjNjOTMzODciLCJzY29wZWRLZXlTZWNyZXQiOiIzMWJlYzBkZDU0NDFlNWRkMWMyMGYzMmE0ODdlNGU4ZmU0ODYzM2Y0MGJlNWM3MTM2MGRiNDczZTY4NWQwNzAzIiwiaWF0IjoxNzAwMjQzNjI4fQ.6mRg0kqfyhvc7Zk6OhqTnf5NNgPY0iuJi_C6WKPHrDc"
      MNEMONIC: "mirror spice begin hurry shrug upon kite tray awake embark dutch wall plate tape mimic pigeon virus raw faith student like crane indoor canvas"
      TONCENTER_API_KEY: "29f82419a75cce77993d157299032241584792e659c9c9fc2c61c17ba369eb23"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4.0.0
        with: 
          node-version: "18"
          cache: '${{ steps.detect-package-manager.outputs.manager }}'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: './dist'
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.9
